#!/usr/bin/perl
$| = 1;

print "Scanning for local apache/cgiwrap directories to rebuild...\n";

chdir("/");

opendir( DIR, "/local" );
while ( $file = readdir(DIR) )
{
	if ( $file eq "apache-root" || $file =~ /apache-root-.*/ )
	{
		if ( -e "/local/$file/cgiwrap" )
		{
			print "Building in /local/$file/cgiwrap:\n";
			chdir("/local/$file/cgiwrap") || next;
			&mysystem("/local/apache/build-cgiwrap");
			chdir("/");
			print "\n\n";
		}
	}
}
closedir(DIR);

sub mysystem
{
	my ($cmd) = @_;
	print "+ $cmd\n";
	system($cmd);
}
